name: Actions Runner Controller Demo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
#  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
      - run: echo "ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ğŸ‰ This job uses runner scale set runners!"

  converge:
    name: Converge
    runs-on: arc-runner-set

    permissions:
      contents: read
      packages: write

    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install git -y
          sudo apt install buildah -y

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: Buildah Build
#        uses: redhat-actions/buildah-build@v2

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run script
        run: |
          ls -al
          . $(werf ci-env github --as-file)
          env
          werf converge

#        env:
#          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
#          WERF_ENV: production
